##### DECLARATIONS #####
# Variables
variables:
  Major: $[format('{0:yyyy}', pipeline.startTime)]
  Minor: $[format('{0:m}', pipeline.startTime)]
  Patch: $[counter(format('{0}.{1}', variables['Major'], variables['Minor']), 1)]

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Version: $(Major).$(Minor).$(Patch)"
  displayName: 'Read IronDrawing Version'
- script: |
    echo "Version: $(Major).$(Minor).$(Patch)"
  displayName: 'Read IronDrawing Version (Again)'
