##### DECLARATIONS #####
# Variables
variables:
  - group: IronDrawingVersions
  - name: NuGetVersion
    value: $(IronDrawingMajorVersion).$(IronDrawingMinorVersion).$(IronDrawingPatchVersion)

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Version: $(Major).$(Minor).$(Patch)"
  displayName: 'Read IronDrawing Version'
