##### DECLARATIONS #####
# Variables
variables:
  - group: IronDrawingVersions
  - name: NuGetVersion
    value: $(IronDrawingMajorVersion).$(IronDrawingMinorVersion).$(IronDrawingPatchVersion)

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Version (Variables): $(Major).$(Minor).$(Patch)"
    echo "Version: $(IronDrawingMajorVersion).$(IronDrawingMinorVersion).$(IronDrawingPatchVersion)"
    echo "NuGetVersion: $(NuGetVersion)"
  displayName: 'Read IronDrawing Version'
